# docker-compose.yml

version: "3.9"
services:
  ssh_server_classic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssh_server_classic
    command: ["/scripts/start_classic.sh"]
    volumes:
      - ./scripts:/scripts
    ports:
      - "2222:22"
    networks:
      - global-net

  ssh_server_pqc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssh_server_pqc
    command: ["/scripts/start_pqc.sh"]
    volumes:
      - ./scripts:/scripts
    ports:
      - "2223:22"
    networks:
      - global-net

  ssh_client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssh_client
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./scripts:/scripts
      - ./tmp:/tmp
    networks:
      - global-net

  toy_server:
    build:
      context: .
      dockerfile: Dockerfile_toy_ssh
    container_name: toy_server
    volumes:
      - ./demo_shared:/app
    command: ["python", "server.py"]
    ports:
      - "2222:2222"
    networks:
      - global-net

  toy_client:
    build:
      context: .
      dockerfile: Dockerfile_toy_ssh
    container_name: toy_client
    depends_on:
      - toy_server
    volumes:
      - ./demo_shared:/app
    command: ["bash", "-c", "sleep 1 && python client.py"]
    networks:
      - global-net

networks:
  global-net:
    external: true