# docker-compose.yml

version: "3.9"
services:
  ssh_server_classic:
    build: .
    container_name: ssh_server_classic
    command: ["/scripts/start_classic.sh"]
    volumes:
      - ./scripts:/scripts
    ports:
      - "2222:22"
    networks:
      - global-net

  ssh_server_pqc:
    build: .
    container_name: ssh_server_pqc
    command: ["/scripts/start_pqc.sh"]
    volumes:
      - ./scripts:/scripts
    ports:
      - "2223:22"
    networks:
      - global-net

  ssh_client:
    build: .
    container_name: ssh_client
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./scripts:/scripts
      - ./tmp:/tmp
    networks:
      - global-net

networks:
  global-net:
    external: true